### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by hoangt** [georgia-tech-synergy-lab/MAESTRO#1]
Nice to see this tool online. Some minor fixes can be updated
1) In run.sh
--dataflow_file='data/dataflow/**prs**.m' -> --dataflow_file='data/dataflow/**rs**.m'
2) Update README file
-- Indicate compiling code with g++-6 or higher
-- Indicate boost library version (1.65 or higher)

**Comment by hyoukjun** [comment]
Thank you for letting me know about it. I found the same issue in run.sh so I pushed a fix. I'll also mention the versions in the README file.
